#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-som
Version  : 0.3.5.1
Release  : 7
URL      : https://cran.r-project.org/src/contrib/som_0.3-5.1.tar.gz
Source0  : https://cran.r-project.org/src/contrib/som_0.3-5.1.tar.gz
Summary  : Self-Organizing Map
Group    : Development/Tools
License  : GPL-3.0
Requires: R-som-lib
BuildRequires : clr-R-helpers

%description
No detailed description available

%package lib
Summary: lib components for the R-som package.
Group: Libraries

%description lib
lib components for the R-som package.


%prep
%setup -q -c -n som

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1521301833

%install
rm -rf %{buildroot}
export SOURCE_DATE_EPOCH=1521301833
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library som
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library som
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library som
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc -l %{buildroot}/usr/lib64/R/library som|| : 
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/som/DESCRIPTION
/usr/lib64/R/library/som/INDEX
/usr/lib64/R/library/som/Meta/Rd.rds
/usr/lib64/R/library/som/Meta/data.rds
/usr/lib64/R/library/som/Meta/features.rds
/usr/lib64/R/library/som/Meta/hsearch.rds
/usr/lib64/R/library/som/Meta/links.rds
/usr/lib64/R/library/som/Meta/nsInfo.rds
/usr/lib64/R/library/som/Meta/package.rds
/usr/lib64/R/library/som/NAMESPACE
/usr/lib64/R/library/som/R/som
/usr/lib64/R/library/som/R/som.rdb
/usr/lib64/R/library/som/R/som.rdx
/usr/lib64/R/library/som/data/yeast.tab.bz2
/usr/lib64/R/library/som/help/AnIndex
/usr/lib64/R/library/som/help/aliases.rds
/usr/lib64/R/library/som/help/paths.rds
/usr/lib64/R/library/som/help/som.rdb
/usr/lib64/R/library/som/help/som.rdx
/usr/lib64/R/library/som/html/00Index.html
/usr/lib64/R/library/som/html/R.css
/usr/lib64/R/library/som/libs/symbols.rds

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/som/libs/som.so
/usr/lib64/R/library/som/libs/som.so.avx2
/usr/lib64/R/library/som/libs/som.so.avx512
